_homepage:
    pattern:  /
    defaults: { _controller: WebomageMessageBundle:Message:index }

_msgform:
    pattern:  /msgform/
    defaults: { _controller: WebomageMessageBundle:Message:msgform }

_msgformsubmit:
    pattern:  /msgformsubmit/
    defaults: { _controller: WebomageMessageBundle:Message:msgformsubmit }
