parameters:
#    webomage_message.example.class: Webomage\MessageBundle\Example

services:
#    webomage_message.example:
#        class: %webomage_message.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
